name: CI

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  scan_ruby:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: Scan for common Rails security vulnerabilities using static analysis
        run: bin/brakeman --no-pager

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: Lint code for consistent style
        run: bin/rubocop -f github

  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16
        ports:
          - "5432:5432"
        env:
          POSTGRES_DB: seat_allocation_service_test
          POSTGRES_USER: rails
          POSTGRES_PASSWORD: password
        options: >-
          --health-cmd="pg_isready -U rails -d seat_allocation_service_test"
          --health-interval=5s
          --health-timeout=5s
          --health-retries=20

    env:
      RAILS_ENV: test
      DATABASE_URL: "postgres://rails:password@postgres:5432/seat_allocation_service_test"

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: Wait for Postgres
        run: |
          for i in {1..30}; do
            pg_isready -h postgres -U rails -d seat_allocation_service_test && exit 0
            sleep 1
          done
          echo "Postgres did not become ready in time" >&2
          exit 1
        env:
          PGPASSWORD: password

      - name: Set up database
        run: bin/rails db:test:prepare

      - name: Run tests
        run: bin/rspec
